apiVersion: backstage.io/v1beta1
kind: Domain
metadata:
  name: ecommerce
  description: Everything related to ecommerce
  title: Ecommerce Services
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: user:dileep
